language: node_js
node_js:
  - "12.13"

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "yoda.github@gmail.com"
  api_token: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: release